services:
  db:
    stop_grace_period: 1s
    image: postgres:18.1-alpine3.23
    environment: 
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    stop_grace_period: 0s
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    build: backend
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/src
  
  frontend:
    stop_grace_period: 1s
    build: frontend
    ports:
      - 3001:3001
    environment:
      NEXT_PUBLIC_GRAPHQL_API_URL: http://localhost:4000/graphql
      GRAPHQL_API_URL_SSR: http://backend:4000/graphql
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  postgres_data:
